version: "2"

services:
    service-a:
        build: ./service-a
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
        expose:
            - "8080"
        ports:
            - "8080:80"
        depends_on:
            - service-b
        labels:
            com.microsoft.acs.dcos.marathon.vhost: peterjacs3agents.westus.cloudapp.azure.com

    service-b:
        build: ./service-b
        environment:
            - APPINSIGHTS_INSTRUMENTATIONKEY
        expose:
            - "80"